const timelineData = [
  { era: "Pre-Human Era", date_string: "13.8 Billion years ago", description: "The Big Bang" },
  { era: "Pre-Human Era", date_string: "4.5 Billion years ago", description: "Formation of Planet Earth" },
  { era: "Pre-Human Era", date_string: "4.0 Billion years ago", description: "Earliest Life on Earth" },
  { era: "Pre-Human Era", date_string: "55 Million years ago", description: "Earliest Primates" },
  { era: "Human Evolution", date_string: "2.8 Million years ago", description: "Earliest Human Ancestors (Homo sp.)" },
  { era: "Human Evolution", date_string: "1.5 Million years ago", description: "Control of Fire" },
  { era: "Human Evolution", date_string: "315,000 years ago", description: "First Homo Sapiens" },
  { era: "Hunter-Gatherer Society", date_string: "170,000 years ago", description: "Widespread Use of Clothing" },
  { era: "Hunter-Gatherer Society", date_string: "23,000 years ago", description: "Domestication of Dogs" },
  { era: "Agricultural Revolution", date_string: "9500 BCE", description: "Dawn of Farming" },
  { era: "Agricultural Revolution", date_string: "9000 BCE", description: "First Permanent Settlements (Jericho)" },
  { era: "Agricultural Revolution", date_string: "3300 BCE", description: "The Bronze Age Begins" },
  { era: "Agricultural Revolution", date_string: "3200 BCE", description: "Invention of Writing (Cuneiform)" },
  { era: "Empires & Conquests", date_string: "2560 BCE", description: "The Great Pyramid of Giza is completed" },
  { era: "Empires & Conquests", date_string: "1050 BCE", description: "The Iron Age Begins" },
  { era: "Empires & Conquests", date_string: "630 BCE", description: "First Use of Coinage" },
  { era: "Empires & Conquests", date_string: "500 BCE", description: "Height of Greek Civilization" },
  { era: "Empires & Conquests", date_string: "30 BCE", description: "Death of Cleopatra" },
  { era: "Empires & Conquests", date_string: "27 BCE", description: "Roman Empire Established" },
  { era: "Empires & Conquests", date_string: "30 CE", description: "Life of Jesus of Nazareth" },
  { era: "The Post-Classical Era", date_string: "c. 400 CE", description: "The Hindu-Arabic numeral system spreads from India." },
  { era: "The Post-Classical Era", date_string: "622 CE", description: "The beginning of the Islamic calendar and the rise of Islam." },
  { era: "The Post-Classical Era", date_string: "c. 790 CE", description: "The Islamic Golden Age begins, a period of great scientific and cultural advancement." },
  { era: "The Post-Classical Era", date_string: "1044 CE", description: "The formula for gunpowder is recorded in China." },
  { era: "The Post-Classical Era", date_string: "1215 CE", description: "The Magna Carta is signed, limiting the power of monarchs." },
  { era: "The Post-Classical Era", date_string: "1346 CE", description: "The Black Death pandemic begins, reshaping societies in Eurasia." },
  { era: "Scientific Revolution", date_string: "1440 CE", description: "Invention of the Printing Press" },
  { era: "Scientific Revolution", date_string: "1492 CE", description: "Columbus Reaches the Americas" },
  { era: "Scientific Revolution", date_string: "1543 CE", description: "Copernicus's Heliocentric Model" },
  { era: "Scientific Revolution", date_string: "1687 CE", description: "Newton's Laws of Motion and Gravitation" },
  { era: "Industrial Revolution", date_string: "1769 CE", description: "The Steam Engine" },
  { era: "Industrial Revolution", date_string: "1825 CE", description: "First Public Railway" },
  { era: "Industrial Revolution", date_string: "1876 CE", description: "Invention of the Telephone" },
  { era: "Industrial Revolution", date_string: "1886 CE", description: "First Gasoline-Powered Car" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1903 CE", description: "First Powered Flight" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1928 CE", description: "Discovery of Penicillin" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1945 CE", description: "The Atomic Bomb" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1947 CE", description: "The Transistor" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1957 CE", description: "First Satellite in Orbit (Sputnik)" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1961 CE", description: "First Human in Space" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1969 CE", description: "First Human on the Moon" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1971 CE", description: "The first Microprocessor" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "1989 CE", description: "Invention of the World Wide Web" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2001 CE", description: "First Draft of the Human Genome Sequenced" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2007 CE", description: "The first iPhone is released" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2012 CE", description: "CRISPR gene editing technology developed" },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2017 CE", description: "The \"Transformer\" architecture is introduced, paving the way for modern AI." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2020 CE", description: "The COVID-19 Pandemic begins." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2020 CE", description: "AlphaFold solves the protein folding problem, a major scientific breakthrough." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2021 CE", description: "The James Webb Space Telescope is launched." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2022 CE", description: "Public release of powerful text-to-image models (e.g., Stable Diffusion)." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2022 CE", description: "ChatGPT is released, bringing conversational AI to the masses." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2022 CE", description: "A major breakthrough in nuclear fusion ignition is achieved." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2023 CE", description: "Release of GPT-4, a more powerful and capable AI model." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2024 CE", description: "First comprehensive AI law is passed (EU AI Act)." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2024 CE", description: "Release of advanced text-to-video models like Sora." },
  { era: "Technological Revolution & The Great Acceleration", date_string: "2025 CE (Projected)", description: "AI agents begin to make independent scientific discoveries." },
];
